// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chenmuyao/go-bootcamp/interactive/events"
	"github.com/chenmuyao/go-bootcamp/interactive/grpc"
	"github.com/chenmuyao/go-bootcamp/interactive/ioc"
	"github.com/chenmuyao/go-bootcamp/interactive/repository"
	"github.com/chenmuyao/go-bootcamp/interactive/repository/cache/rediscache"
	"github.com/chenmuyao/go-bootcamp/interactive/repository/dao"
	"github.com/chenmuyao/go-bootcamp/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := rediscache.NewInteractiveRedisCache(cmdable)
	topArticlesCache := ioc.InitTopArticlesCache()
	interactiveRepository := repository.NewCachedInteractiveRepository(logger, interactiveDAO, interactiveCache, topArticlesCache)
	client := ioc.InitSaramaClient()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(logger, interactiveRepository, client)
	v := ioc.InitConsumers(interactiveReadEventConsumer)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.NewGrpcxServer(interactiveServiceServer)
	app := &App{
		consumers: v,
		server:    server,
	}
	return app
}

func InitInteractiveRepo() repository.InteractiveRepository {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := rediscache.NewInteractiveRedisCache(cmdable)
	topArticlesCache := ioc.InitTopArticlesCache()
	interactiveRepository := repository.NewCachedInteractiveRepository(logger, interactiveDAO, interactiveCache, topArticlesCache)
	return interactiveRepository
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitRedis, ioc.InitDB, ioc.InitLogger, ioc.InitSaramaClient)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, rediscache.NewInteractiveRedisCache, ioc.InitTopArticlesCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)
