services:
  mysql:
    image: mysql:9
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - 13316:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 13317:8080
