# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wetravel-mysql-pv
  labels:
    app: wetravel-mysql-pv
spec:
  storageClassName: wetravel
  # supported accessModes
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    # path of this PV
    path: "/mnt/data"
---

