# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wetravel-mysql-pvc
  labels:
    app: wetravel-mysql-pvc
spec:
  storageClassName: wetravel
  # Read write by one Pod (the pod of mysql)
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

