// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/limiter/types.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/limiter/types.go -package=limitermocks -destination=./pkg/limiter/mocks/limiter.mock.go
//

// Package limitermocks is a generated GoMock package.
package limitermocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLimiter is a mock of Limiter interface.
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
	isgomock struct{}
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter.
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance.
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// AcceptConnection mocks base method.
func (m *MockLimiter) AcceptConnection(ctx context.Context, biz string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptConnection", ctx, biz)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcceptConnection indicates an expected call of AcceptConnection.
func (mr *MockLimiterMockRecorder) AcceptConnection(ctx, biz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptConnection", reflect.TypeOf((*MockLimiter)(nil).AcceptConnection), ctx, biz)
}
